# Jekyll Portfolio

name: Matthew Lean
email: mttlean@gmail.com
highlighter: rouge
exclude: ["node_modules", "gulpfile.js", "package.json"]
destination: ./_site
sass:
  sass_dir: ./_scss
  style: compressed
