# Jekyll Portfolio

name: Matthew Lean
email: mttlean@gmail.com
title: Matthew Lean - Digital Designer
description: I'm a Digital Designer, I mainly design websites, logos and branding. Check out my blog for my latest projects and email me if you'd like to work together.
logo: /assets/site-brand/matthew-lean.jpg

highlighter: rouge
exclude: ["node_modules", "gulpfile.js", "package.json"]
# destination: ./_site
sass:
  sass_dir: ./_scss
  style: compressed
incremental: true