# Jekyll Portfolio

name: Matthew Lean
email: mttlean@gmail.com
title: Matthew Lean - Bournemouth Digital Designer
description: Matthew Lean's Portfolio - Bournemouth based Digital Designer. I design websites & create branding and logos. I enjoy photography & cooking and post mainly food on Instagram.
logo: /assets/site-brand/matthew-lean.jpg

highlighter: rouge
exclude: ["node_modules", "gulpfile.js", "package.json"]


# destination: ./_site
sass:
  sass_dir: ./_scss
  style: compressed

incremental: true

plugins:
  - jekyll-redirect-from