# Jekyll Portfolio

name: Matthew Lean
email: mttlean@gmail.com
title: Matthew Lean - Bournemouth Digital Designer
description: I'm a Digital Designer, I mainly design websites, but also work with branding and logos. I enjoy photography & cooking and post mainly food on Instagram. Check out my projects for my latest work and email me if you'd like to work together.
logo: /assets/site-brand/matthew-lean.jpg

highlighter: rouge
exclude: ["node_modules", "gulpfile.js", "package.json"]


# destination: ./_site
sass:
  sass_dir: ./_scss
  style: compressed

incremental: true

plugins:
  - jekyll-redirect-from